enum AppActionTypes {
    AT_TAB_CHANGED,
    AT_SELECTION_CHANGED,
    AT_NEW_ITEM_REQUESTED,
    AT_NEW_ITEM_ABORTED,
    AT_NEW_ITEM_CONFIRMED,
    AT_ITEM_CHANGE_ABORTED,
    AT_ITEM_CHANGE_CONFIRMED,
    AT_LOAD_DATA_REQUESTED,
    AT_DATA_LOADED,
    AT_DATA_LOAD_FAILED,
    AT_DELETE_ITEM
}

export = AppActionTypes ;